- name: Good First Issue
  color: "c8356e"
  description: "A great place to start if you're new to contributing"
- name: Accessibility (a11y)
  color: "646970"
  description: "Changes that impact accessibility"
- name: Internationalization (i18n)
  color: "907300"
- name: First-time Contributor
  color: "704000"
  description: "Pull request opened by a first-time contributor"
- name: "[Type] Enhancement"
  color: "984a9c"
  description: "Something new that adds functionality"
- name: "[Type] Bug"
  color: "8a2424"
- name: "[Type] WP Core Bug"
  color: "006088"
- name: "[Type] Maintenance"
  color: "2271b1"
  description: "Minor file cleanup and organization tasks"
- name: "[Status] In Progress"
  color: "017e65"
  description: "Tracking issues with work in progress"
- name: "[Status] Needs Info"
  color: "017e65"
  description: "Follow-up required in order to be actionable"
- name: "[Status] Stale"
  color: "017e65"
  description: "Gives the original author opportunity to update before closing; can be reopened as needed"
- name: "[Status] Invalid"
  color: "017e65"
  description: "Issue outside this project; not a valid issue"
- name: "[Status] Won't Fix"
  color: "017e65"
  description: "Issues/PRs we will (likely) not implement"
- name: "[Priority] Low"
  color: "007017"
- name: "[Priority] High"
  color: "b26200"
- name: "[Priority] Critical"
  color: "d63638"
